Filled in the i2c_interface_to_mbed class' .hpp and .cpp
Filled in the i2c_interface_to_mbed class' .hpp and .cpp, however the current version doesn't compile due to :
CMakeFiles/eurobot2019_i2c_interface_node.dir/i2c_interface_node.cpp.o: In function `main':
i2c_interface_node.cpp:(.text+0x1bd): undefined reference to `I2C_interface_to_mbed::I2C_interface_to_mbed()'
i2c_interface_node.cpp:(.text+0xbf1): undefined reference to `I2C_interface_to_mbed::send_grabber_i2c_msg(eurobot2019_messages::grabber_motors_<std::allocator<void> > const&)'
i2c_interface_node.cpp:(.text+0xc0a): undefined reference to `I2C_interface_to_mbed::send_dropper_i2c_msg(eurobot2019_messages::drop_motors_<std::allocator<void> > const&)'
i2c_interface_node.cpp:(.text+0xc23): undefined reference to `I2C_interface_to_mbed::send_drive_i2c_msg(geometry_msgs::Twist_<std::allocator<void> > const&)'
i2c_interface_node.cpp:(.text+0xc78): undefined reference to `I2C_interface_to_mbed::get_dropper_i2c_msg(eurobot2019_messages::drop_status_<std::allocator<void> >&)'
i2c_interface_node.cpp:(.text+0xc91): undefined reference to `I2C_interface_to_mbed::get_drive_i2c_msg(std::vector<float, std::allocator<float> >&)'
i2c_interface_node.cpp:(.text+0xdd5): undefined reference to `I2C_interface_to_mbed::~I2C_interface_to_mbed()'
i2c_interface_node.cpp:(.text+0x123d): undefined reference to `I2C_interface_to_mbed::~I2C_interface_to_mbed()'